RC 1
* do purge in parallel

* safety check on max_simultaneous_rollups

* MapAll logging

* Simplify startup & accumulators
- relies on metadata more (can be added in emergency with reconcile)
- rolls up all hanging currents if it can
- ignores entries without metadata
- don't run two h3flushes at the same time
- remove [currentAccumulator] just use one set

* Rework initial rollup
- handle duplicate station IDs by merging
- fix stats adding up error
- adopt all hanging currents that can still be merged
- startup stats
- record effectiveStart for accumulators into metadata
- move rollup to be closer to the start of the period, and use timeouts so no drift

* Airspace toggle
- Airspace key in config

* Ignore packets without timestamp

* New Deck Version

* Batched write of arrow

* Wrong timeout calculation

* backwards compatibility


* LetsEncrypt

* Update Dockerfile

* Environment variables without rebuild

* Dynamic JSONs
- confirm station/file is valid before using
- scan the directory to find the list of files rather than using the exported .json so that it's easier to delete files

* tidier purge logging
- always log on a purge
- don't purge till process has been running for at least purge time
* show version

diff --git a/conf/Dockerfile b/conf/Dockerfile
--- a/conf/Dockerfile
+++ b/conf/Dockerfile
@@ -1,5 +1,5 @@
 # disposable to find github version, only used for that
-FROM node:16-alpine as version
+FROM node:18.16-alpine as version
 WORKDIR /ognrange
 COPY .git/HEAD .git/HEAD
 COPY .git/refs/heads .git/refs/heads
@@ -7,10 +7,7 @@ COPY ./conf/.env.local ./.env.local
 RUN echo "NEXT_PUBLIC_GIT_REF=$(cat /ognrange/.git/`cat .git/HEAD | cut -f2 -d ' '`)" >> ./.env.local
 
 ######## builders
-FROM node:16-alpine as gyp
-RUN apk add --no-cache flock curl
-WORKDIR /ognrange
-COPY --from=version /ognrange/.env.local ./.env.local
+FROM node:18.16-alpine as gyp
 
 FROM gyp as build-image
 WORKDIR /ognrange
@@ -21,19 +18,23 @@ COPY ./yarn.lock ./
 RUN apk add --no-cache --virtual .build-deps alpine-sdk python3 && npm_config_build_from_source=true yarn install --frozen-lockfile && apk del .build-deps
 
 FROM build-image AS next-build-image
-COPY ./next.config.cjs ./next.config.cjs
+COPY ./next.config.js ./next.config.js
+COPY ./tsconfig.json ./tsconfig.json
 COPY ./styles ./styles
 COPY ./lib/common ./lib/common
 COPY ./lib/api ./lib/api
 COPY ./pages ./pages
 COPY ./lib/react ./lib/react
+COPY --from=version /ognrange/.env.local ./.env.local
 RUN yarn next build
 
 FROM build-image AS aprs-build-image
 COPY ./lib/common ./lib/common
 COPY ./bin ./bin
 COPY ./lib/bin ./lib/bin
+COPY ./lib/worker ./lib/worker
 COPY ./tsconfig-bin.json ./tsconfig-bin.json
+COPY --from=version /ognrange/.env.local ./.env.local
 RUN yarn aprs:build
 
 
@@ -44,25 +45,37 @@ COPY ./package.json ./
 COPY ./yarn.lock ./
 RUN apk add --no-cache --virtual .build-deps alpine-sdk python3 && npm_config_build_from_source=true yarn install --production  --frozen-lockfile && apk del .build-deps
 
-FROM base-image AS next
-HEALTHCHECK --interval=10s --retries=5 CMD curl -Q --fail http://localhost:3000 || exit 1
+FROM node:18.16-alpine AS next
+#HEALTHCHECK --interval=10s --retries=5 CMD curl -Q --fail http://localhost:3000 || exit 1
+HEALTHCHECK --interval=10s --retries=5 CMD wget --no-verbose --tries=1 --spider http://next:3000/ || exit 1
 WORKDIR /ognrange
-COPY --from=next-build-image /ognrange/.next ./.next
-COPY ./public ./public
-COPY ./next.config.cjs ./next.config.cjs
+#COPY --from=next-build-image /ognrange/.next/standalone ./
+COPY --from=next-build-image /ognrange/node_modules ./node_modules
+COPY ./next.config.js ./next.config.js
 COPY ./LICENSE ./LICENSE
+COPY ./package.json ./
+COPY ./public ./public
+COPY --from=next-build-image /ognrange/.next/static ./.next/static
+COPY --from=next-build-image /ognrange/.next/ ./.next/
 EXPOSE 3000
 CMD yarn next start
 
-FROM base-image AS aprs
+FROM node:18.16-alpine AS aprs
 HEALTHCHECK --interval=10s --retries=5 CMD flock --exclusive --nonblock /ognrange/data/db/status/LOCK  --command 'echo lock failed' || exit 1
 WORKDIR /ognrange
 RUN mkdir data
 COPY --from=aprs-build-image /ognrange/dist ./dist
+COPY --from=aprs-build-image /ognrange/package.json .
+COPY --from=aprs-build-image /ognrange/.env.local ./.env.local
+COPY --from=aprs-build-image /ognrange/node_modules ./node_modules
 CMD node dist/bin/aprs.js
 
 FROM httpd:2.4-alpine AS apache
-HEALTHCHECK --interval=10s --retries=5 CMD curl -Q --fail http://localhost:8000 || exit 1
+HEALTHCHECK --interval=10s --retries=5 CMD wget --no-verbose --tries=1 --spider http://apache:8000/ || exit 1
+# curl -Q --fail http://localhost:8000 || exit 1
 RUN apk add --no-cache curl
 RUN mkdir -p /ognrange/data
+EXPOSE 8443
+EXPOSE 8000
 COPY ./conf/docker-httpd.conf /usr/local/apache2/conf/httpd.conf
+COPY ./conf/nope.html /ognrange/data/
